version: "3.8"
services:
  shinyapps:
    build: .

    ports:
      - "3838:3838" # host:container
    container_name: shinyapps
    extra_hosts:
      - "host.docker.internal:host-gateway"
#adding environment variables
    environment:
      - MONGO_HOST=mongodba
      - MONGO_PORT=27017
    depends_on:
      - mongodba
  mongodba:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodba
    volumes:
      #- ./data/db:/data/db:ro
     # - ./TrialCurate/data/trials:/data/trials
     # - ./TrialCurate/mongo/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh:ro

      # - ./data/trials:/data/trials
       - ./data/trials:/data/trials:ro
       - ./mongo/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh:ro

    #Install mongo-tools for using mongoimport
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y mongo-tools"



